### ISSUE TITLE
Masks seems doesn't work

### ISSUE THREAD

**Issue by liweijian** [screenshotbot/screenshotbot-oss#11] opened 2021-09-27 09:25 UTC
I just added some masks for the screenshots as follows, however, it seems not worked as expected.

<img width=600 src="https://user-images.githubusercontent.com/19320783/134881639-c92e57b5-a961-430e-aba2-9731985f51dc.png">

<img width=600 src="https://user-images.githubusercontent.com/19320783/134881901-54f9e01b-0174-44ac-9ba5-377334c39fbe.png">

**Comment by tdrhq** [comment] 2021-09-27 14:58
Got it, so the "Compare" link unfortunately shows comparisons including the ones under the mask. The mask is only used to generate reports. So there might be a pixel outside the mask that's still changing. 

There's no automated tool in Screenshotbot to help with this at the moment. I'll improve the Compare images to remove out the mask. 

(However, I'm in the process of a move, so I'll be slow in making changes over the next week, I'll still respond on GitHub when I get a chance. This will most likely be done by next Tuesday or Wednesday)

**Comment by tdrhq** [comment] 2021-10-05 15:05
Just keeping you updated, I'm working on this. My fix will be two parts:

a) First I'll update the compare tool to zoom into only a pixel outside the mask (this is a recently added tool, not sure if you've seen this as yet: https://docs.screenshotbot.io/docs/comparing-images/#compare). At this point even though you'll see red pixels for changes under the mask, you'll still be able to zoom into the ones that matter.

b) Then we'll update the compare view to show the pixels under the mask differently.

I'm still doing a lot of move-related things, so I expect to be done with (a) in the next two days and then (b) soon after

**Comment by tdrhq** [comment] 2021-10-06 16:36
Fixed the bug mentioned in the previous comment (https://github.com/screenshotbot/screenshotbot-oss/commit/8caf8b693ae6c7c24cd151de83c417cc75bf7009)

I'm going to close this Issue. But let me know if you're able to use these updated tools to pin-point which pixel changed. If there's no pixel changes outside of the mask (you would probably get an error while trying to zoom in), then let me know: it would mean that there's a bug where we're not looking at the masks during the report generation.

**Closed by tdrhq** 2021-10-06 16:36 UTC

**Comment by tdrhq** [comment] 2021-10-06 16:44
One more note: The "Zoom to Change" button is computationally intensive, especially when using masks (it runs in O(H * W * (M + 1)) time, H=height, W=width, M=number of masks),. It takes a few seconds on LispWorks. Clozure CL doesn't optimize code as much so it might be even slower. There's a lot of room for improvement (both algorithmic, and low-level programming optimizations), so let me know if it's unbearably slow for you.

**Comment by liweijian** [comment] 2021-10-11 10:08
And the good news is I used another docker server to start a new services, and it works well:
![image](https://user-images.githubusercontent.com/19320783/136772536-98d39fcf-00fd-416a-88af-fc3801ac613a.png)

But the all pixel comparisons not changed as above:
![image](https://user-images.githubusercontent.com/19320783/136772782-e4675e1f-36b8-4854-8206-a56b01c5fce9.png)

**Comment by tdrhq** [comment] 2021-10-11 14:28
Hmm, that error is no fun. Let me give you some context. The datastore we use is bknr.datastore, which is an in-memory store with transactions written to disk. (So if you ever do `obj.y = 20` --- `(setf (obj-y obj) 20)` --- it changes that in memory and write a transaction on disk saying that that has changed.) Every few hours we write a snapshot to disk. So when you restart the service, it reloads the snapshot, and replays the transactions.

So it looks like we're failing to reload the current version of the data store. In particular, it's failing when applying the transactions after reading the snapshot. The specific transaction that it's trying to apply is telling me something about what the bug could potentially be.

In particular, the transaction is related to the notion of "singleton" company. More context: On my production system, there are multiple companies, and users can create their own companies. On OSS, by default---can be changed, there's one singleton company. This company is created in this code: 
https://github.com/screenshotbot/screenshotbot-oss/blob/main/src/screenshotbot/model/company.lisp#L275

Basically: under a lock, check if a company already exists, if so return that, otherwise create a new one.

What I think happened here, is that this function got called *while* the bknr.datastore was starting up. (This can happen because bknr.datastore objects are just Lisp objects that have their own constructors etc.) At this point the singleton company maybe didn't exist yet, so it created a new one. bknr.datastore doesn't handle this very well, and it'll write a new transaction to the transaction log even though it's currently loading things from it. And now there is a bad transaction in the log that cannot be replayed if everything loaded correctly.

There are a few things you can try. You can switch to the previous snapshot. (That's just moving the dated directory in `~/.config/screenshotbot/object-store` to the `current` directory. Keep backups of both those directories). But that doesn't solve the root cause of the problem. Let me create you some tools so you can do this safely, and put some assertions to make sure at least my hypothesis doesn't happen again.. I'll open another Issue for tracking this.

**Comment by tdrhq** [comment] 2021-11-28 19:15
@liweijian with respect to your original issue, about masks not working. Turns out there was indeed a bug, where we were using the wrong masks for comparison. (So if we were comparing a screenshot A to its previous version B, we used the masks from B instead of A. So the first time a change happens after setting a mask, the mask won't have effect.)

I've fixed this in: https://github.com/screenshotbot/screenshotbot-oss/commit/66d8b5427487b69d8deb16ceb6f995d3676bbd58
